In [ ]:
from bs4 import BeautifulSoup
import requests
url = "https://stats.espncricinfo.com/ci/engine/player/34102.html?class=2;template=results;type=allround"
req = requests.get(url)
soup = BeautifulSoup(req.text, "html.parser")
print(soup.title)

<title>All-round records | One-Day Internationals | Cricinfo Statsguru | ESPNcricinfo.com</title>

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
webpage = requests.get('https://stats.espncricinfo.com/ci/engine/player/34102.html?class=2;template=results;type=allround').text

In [ ]:
soup = BeautifulSoup(webpage,'lxml')

In [ ]:
#table_list = (soup.find_all('table')[0])

In [ ]:
table = (soup.find_all('table', class_='engineTable')[2])

In [ ]:
title = (table.find_all('th'))
title_new = []
avg_sum = []
for title in title:
         title_new.append(title.text)
print(title_new)

['Grouping', 'Span', 'Mat', 'Runs', 'HS', 'Bat Av', '100', 'Wkts', 'BBI', 'Bowl Av', '5', 'Ct', 'St', 'Ave Diff', '']

In [ ]:
avg_data = table.find_all('td')
avg_sum=[]
for avg_data in avg_data:
  avg_sum.append(avg_data.text)

print(avg_sum)

['overall', '2007-2023', '252', '10112', '264', '48.61', '30', '8', '2/27', '64.37', '0', '91', '0', '-15.75', 'Profile']

In [ ]:
#caption=[]
#th = []
#for i in table:
#  print('utk' , i)
 # caption.append(i.find_all('caption'))
 # th.append(i.find_all('th', class_='head'))

In [ ]:
df = pd.DataFrame([avg_sum], columns=title_new)

In [ ]:
df

,,Span,Mat,Runs,HS,Bat Av,100,Wkts,BBI,Bowl Av,5,Ct,St,Ave Diff,
0,overall,2007-2023,252,10112,264,48.61,30,8,2/27,64.37,0,91,0,-15.75,Profile

In [ ]:
# working fin till this

In [ ]:
table = (soup.find_all('table', class_='engineTable')[3])

In [ ]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)

In [ ]:
career_summary = (table.find_all('tr'))
#title_new1 = []
#for Career_title in Career_title:
#         title_new1.append(Career_title.find_all('td').text)
#print(title_new1)

In [ ]:

car = career_summary[1]
car = car.find_all('td')
car_sum = []
for car in car:
  car_sum.append(car.text.strip())
print(car_sum)

['v Afghanistan', '2014-2019', '2', '19', '18*', '19.00', '0', '-', '-', '-', '-', '0', '0', '-', '']

In [ ]:

car = career_summary[1]
car = car.find_all('td')
car_sum = []
for car in car:
  car_sum.append(car.text.strip())
print(car_sum)

['v Afghanistan', '2014-2019', '2', '19', '18*', '19.00', '0', '-', '-', '-', '-', '0', '0', '-', '']

In [ ]:
x = []
for i in career_summary:

TypeError: ignored

In [ ]:
!pip install html-table-parser-python3

Collecting html-table-parser-python3
  Downloading html_table_parser_python3-0.3.1-py3-none-any.whl (15 kB)
Installing collected packages: html-table-parser-python3
Successfully installed html-table-parser-python3-0.3.1

In [ ]:
# Library for opening url and creating
# requests
import urllib.request

# pretty-print python data structures
from pprint import pprint

# for parsing all the tables present
# on the website
from html_table_parser.parser import HTMLTableParser

# for converting the parsed data in a
# pandas dataframe
import pandas as pd


# Opens a website and read its
# binary contents (HTTP Response Body)
def url_get_contents(url):

	# Opens a website and read its
	# binary contents (HTTP Response Body)

	#making request to the website
	req = urllib.request.Request(url=url)
	f = urllib.request.urlopen(req)

	#reading contents of the website
	return f.read()

# defining the html contents of a URL.
xhtml = url_get_contents('https://stats.espncricinfo.com/ci/engine/player/34102.html?class=2;template=results;type=allround').decode('utf-8')

# Defining the HTMLTableParser object
p = HTMLTableParser()

# feeding the html contents in the
# HTMLTableParser object
p.feed(xhtml)

# Now finally obtaining the data of
# the table required
###pprint(p.tables[3])

# converting the parsed data to
# dataframe
#print("\n\nPANDAS DATAFRAME\n")
df1 = pd.DataFrame(p.tables[3])

In [ ]:
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,Grouping,Span,Mat,Runs,HS,Bat Av,100,Wkts,BBI,Bowl Av,5,Ct,St,Ave Diff,
1,v Afghanistan,2014-2019,2,19,18*,19.00,0,-,-,-,-,0,0,-,
2,v Australia,2007-2023,44,2332,209,58.30,8,2,1/17,32.50,0,13,0,25.80,
3,v Bangladesh,2008-2023,16,738,137,56.76,3,1,1/5,18.00,0,8,0,38.76,
4,v England,2008-2022,19,637,137*,45.50,2,-,-,-,-,4,0,-,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,,None,None,None,None,None,None,None,None,None,None,None,None,None,None
150,tournament finals,2008-2023,11,256,66,25.60,0,0,-,-,0,5,0,-,
151,tournament semi-finals,2013-2019,4,191,123*,63.66,1,-,-,-,-,2,0,-,
152,tournament quarter-finals,2015-2015,1,137,137,137.00,1,-,-,-,-,0,0,-,
153,preliminary matches,2008-2023,78,2990,140,46.71,9,3,1/5,59.33,0,30,0,-12.61,

In [ ]:
table = (soup.find_all('table', class_='engineTable')[3])
data = []
for row in table.find_all('tr'):
    row_data = []
    for cell in row.find_all('td'):
        row_data.append(cell.text)
    data.append(row_data)

In [ ]:
df_new = pd.DataFrame(data)

In [ ]:
df_new

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,v Afghanistan,2014-2019,2,19,18*,19.00,0,-,-,-,-,0,0,-,
2,v Australia,2007-2023,44,2332,209,58.30,8,2,1/17,32.50,0,13,0,25.80,
3,v Bangladesh,2008-2023,16,738,137,56.76,3,1,1/5,18.00,0,8,0,38.76,
4,v England,2008-2022,19,637,137*,45.50,2,-,-,-,-,4,0,-,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,,None,None,None,None,None,None,None,None,None,None,None,None,None,None
150,tournament finals,2008-2023,11,256,66,25.60,0,0,-,-,0,5,0,-,
151,tournament semi-finals,2013-2019,4,191,123*,63.66,1,-,-,-,-,2,0,-,
152,tournament quarter-finals,2015-2015,1,137,137,137.00,1,-,-,-,-,0,0,-,
153,preliminary matches,2008-2023,78,2990,140,46.71,9,3,1/5,59.33,0,30,0,-12.61,